import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "zellij attach || zellij"]

[window]
opacity = 0.95
blur = true
dynamic_padding = true
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 12

[selection]
save_to_clipboard = true
